import streamlit as st
import pandas as pd
import numpy as np

# Page Configuration
st.set_page_config(page_title="Airline Retention Twin", layout="wide", initial_sidebar_state="expanded")

st.title("✈️ Airline Loyalty Intelligence Command Center")
st.markdown("**Executive Operations Dashboard** | Designed for immediate retention interventions.")

# Load the scored data generated by the Jupyter Notebook
@st.cache_data
def load_data():
    try:
        df = pd.read_csv('airline_loyalty_data/scored_members.csv')
        return df
    except FileNotFoundError:
        st.error("CRITICAL ERROR: 'scored_members.csv' not found. Please run the Jupyter Notebook pipeline first to generate the intelligence matrix.")
        return pd.DataFrame()

df = load_data()

if not df.empty:
    st.sidebar.header("🎯 Retention Targeting")
    st.sidebar.markdown("Filter the active member base to identify high-risk cohorts.")
    
    # Dashboard Controls
    risk_threshold = st.sidebar.slider("Minimum Churn Risk %", 50, 99, 75)
    target_segment = st.sidebar.selectbox("Filter by Strategic Segment", ["All Segments"] + list(df['Strategic_Segment'].unique()))
    
    # Filter Logic
    filtered_df = df[df['Churn_Risk_Score'] >= (risk_threshold / 100)]
    if target_segment != "All Segments":
        filtered_df = filtered_df[filtered_df['Strategic_Segment'] == target_segment]
    
    # Top Level Metrics
    st.error(f"🚨 ALERT: {len(filtered_df):,} Members matching current risk profile.")
    
    col1, col2, col3 = st.columns(3)
    col1.metric("Revenue at Risk (CLV)", f"${filtered_df['CLV'].sum():,.0f}")
    col2.metric("Avg Flight Distance Loss", f"{filtered_df['distance_2017'].mean():,.0f} miles")
    col3.metric("Required Action", "Deploy Playbook Protocols")
    
    st.markdown("---")
    st.subheader("📋 Operational Retention Playbook")
    
    # Dynamic Business Logic Matrix
    if target_segment == "Elite Road Warriors" or (target_segment == "All Segments" and len(filtered_df) > 0):
        st.info("**PLAYBOOK A (Elite Road Warriors):** High risk of competitor status-matching. **Action:** Immediate account manager outreach. Offer complimentary immediate upgrade to next tier for 6 months.")
    if target_segment == "High-Value Seasonal" or (target_segment == "All Segments" and len(filtered_df) > 0):
        st.success("**PLAYBOOK B (High-Value Seasonal):** High risk of point hoarding fatigue. **Action:** Send targeted 'Guaranteed Award Seat' voucher for their most frequent historical route.")
    if target_segment == "Occasional Leisure" or (target_segment == "All Segments" and len(filtered_df) > 0):
        st.warning("**PLAYBOOK C (Occasional Leisure):** Price-sensitive drop-off. **Action:** Automated dynamic pricing discount (15% off) on next booking via email.")
    
    st.markdown("---")
    st.subheader("🔍 At-Risk Member Manifest")
    
    # Clean display dataframe
    display_cols = ['Loyalty Number', 'Strategic_Segment', 'CLV', 'flights_2017', 'Churn_Risk_Score']
    st.dataframe(filtered_df[display_cols].sort_values(by='Churn_Risk_Score', ascending=False).head(100).style.format({
        'CLV': '${:,.2f}', 
        'Churn_Risk_Score': '{:.1%}'
    }))